//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DichVu
    {
        public DM_DichVu()
        {
            this.TT_SDDichVu = new HashSet<TT_SDDichVu>();
        }
    
        public string MaDV { get; set; }
        public string TenDV { get; set; }
        public Nullable<decimal> DonGiaVN { get; set; }
        public Nullable<decimal> DonGiaNN { get; set; }
    
        public virtual ICollection<TT_SDDichVu> TT_SDDichVu { get; set; }
    }
}
