//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KhachHang
    {
        public DM_KhachHang()
        {
            this.TT_ThuePhong = new HashSet<TT_ThuePhong>();
        }
    
        public string MaKH { get; set; }
        public string HoTenKH { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string CMND { get; set; }
        public string MaPhanLoai { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QuocTich { get; set; }
    
        public virtual DM_PhanLoaiKH DM_PhanLoaiKH { get; set; }
        public virtual ICollection<TT_ThuePhong> TT_ThuePhong { get; set; }
    }
}
