//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LoaiPhong
    {
        public DM_LoaiPhong()
        {
            this.DM_Phong = new HashSet<DM_Phong>();
        }
    
        public string MaLoaiP { get; set; }
        public string TenLoaiP { get; set; }
    
        public virtual ICollection<DM_Phong> DM_Phong { get; set; }
    }
}
