//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PhanLoaiKH
    {
        public DM_PhanLoaiKH()
        {
            this.DM_KhachHang = new HashSet<DM_KhachHang>();
        }
    
        public string MaPhanLoai { get; set; }
        public string TenPhanLoai { get; set; }
    
        public virtual ICollection<DM_KhachHang> DM_KhachHang { get; set; }
    }
}
