//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Phong
    {
        public DM_Phong()
        {
            this.TT_ThuePhong = new HashSet<TT_ThuePhong>();
        }
    
        public int MaP { get; set; }
        public string TenP { get; set; }
        public string MaLoaiP { get; set; }
        public Nullable<decimal> GiaVN { get; set; }
        public Nullable<decimal> GiaNN { get; set; }
        public Nullable<int> MaTang { get; set; }
    
        public virtual DM_LoaiPhong DM_LoaiPhong { get; set; }
        public virtual DM_Tang DM_Tang { get; set; }
        public virtual ICollection<TT_ThuePhong> TT_ThuePhong { get; set; }
    }
}
