//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_DoiPhong
    {
        public string MaDoiP { get; set; }
        public string MaThue { get; set; }
        public string MaPCu { get; set; }
        public string MaPMoi { get; set; }
        public Nullable<System.DateTime> NgayDenPCu { get; set; }
        public Nullable<System.DateTime> NgayDoiP { get; set; }
    
        public virtual TT_ThuePhong TT_ThuePhong { get; set; }
    }
}
