//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_SDDichVu
    {
        public string MaSDDV { get; set; }
        public string MaThue { get; set; }
        public string MaDV { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> ThanhTienVN { get; set; }
        public Nullable<decimal> ThanhTienNN { get; set; }
    
        public virtual DM_DichVu DM_DichVu { get; set; }
        public virtual TT_ThuePhong TT_ThuePhong { get; set; }
    }
}
