//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_ThuePhong
    {
        public TT_ThuePhong()
        {
            this.DM_HoaDon = new HashSet<DM_HoaDon>();
            this.TT_DoiPhong = new HashSet<TT_DoiPhong>();
            this.TT_SDDichVu = new HashSet<TT_SDDichVu>();
        }
    
        public string MaThue { get; set; }
        public string MaKH { get; set; }
        public Nullable<int> MaP { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<System.DateTime> NgayTraDuKien { get; set; }
        public Nullable<System.DateTime> NgayTraThucTe { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
    
        public virtual ICollection<DM_HoaDon> DM_HoaDon { get; set; }
        public virtual DM_KhachHang DM_KhachHang { get; set; }
        public virtual DM_Phong DM_Phong { get; set; }
        public virtual ICollection<TT_DoiPhong> TT_DoiPhong { get; set; }
        public virtual ICollection<TT_SDDichVu> TT_SDDichVu { get; set; }
    }
}
