//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_TaiKhoan
    {
        public string MaNV { get; set; }
        public string ID { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
    
        public virtual DM_TaiKhoan DM_TaiKhoan { get; set; }
    }
}
